version: "3.8"

services:
    reader:
        build: .
        stdin_open: true
        tty: true
        volumes:
            - .:/app
            - /home/johannes/Documents/Logging/Reader/:/app/logs/
            - /home/johannes/Documents/Python/CO2MonitorReader/app/co2Reader.ini:/app/app/co2Reader.ini
        devices:
            - /dev/hidraw2:/dev/hidraw16
        networks:
            - co2monitor

networks:
    co2monitor:
        external: true
